# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/my_nbdev',
                'doc_host': 'https://paumillet.github.io',
                'git_url': 'https://github.com/paumillet/my_nbdev',
                'lib_path': 'my_nbdev'},
  'syms': {'my_nbdev.core': {'my_nbdev.core.foo': ('core.html#foo', 'my_nbdev/core.py')}}}
